matrix:
    include:
      - language: python
        python: 3.6
        script:
          - pytest Patterns
      - language: cpp
        dist: bionic
        addons:
          apt:
            packages:
              - gcc-7
              - g++-7
              - cmake
        before_script:
          - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
          - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
        script:
          - mkdir build && cd build
          - cmake ..
          - make
          - ctest -VV